name: amd64 Linux

on: [push, pull_request]

jobs:
  linux:
    runs-on: ubuntu-latest
    env:
      VCPKG_ROOT: ./vcpkg
    steps:
    - uses: actions/checkout@v3
    - name: Install XMake
      run: |
        sudo apt-get update
        curl -fsSL https://xmake.io/shget.text | bash
    - name: Check xmake
      run: xmake --version
    - name: Test
      run: make test
    - name: build release
      run: xmake f -m release && make build

