name: amd64 Linux

on: [push, pull_request]

jobs:
  linux:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: xmake-io/github-action-setup-xmake@v1
      with:
        xmake-version: latest
    - name: Test
      run: make test
    - name: build release
      run: xmake f -m release && make build

